### ISSUE TITLE
[BUG] Clicar em modal some com scroll 

### ISSUE THREAD

**Issue by oo7gabriel** [fga-eps-mds/2022-2-EuPescador-Doc#114]
**Descrição do bug**
Ao clicar na modal da listagem de peixes a scroll some.

**Para reproduzir o bug**

O scroll não deveria sumir ao abrir a modal

**Tarefas**

- [ ] Descobrir o motivo do scroll
- [ ] Consertar o bug

**Screenshots**

Imagem da listagem sem scroll
![image](https://user-images.githubusercontent.com/43484906/212522203-707cce00-725b-45e9-abca-99e6dfc4a0cf.png)

Imagem da listagem de peixes com scroll
![image](https://user-images.githubusercontent.com/43484906/212522225-17642f54-062d-43a5-b67a-81393c2bde84.png)

**Comment by emysdias** [comment]
Esse bug vai ser resolvido nesse PR https://github.com/fga-eps-mds/2022-2-EuPescador-Web/pull/30
