### ISSUE TITLE
[Feature] Ajustar ci do arquivo gerado do sonar

### ISSUE THREAD

**Issue by marcelog5** [fga-eps-mds/2022-2-EuPescador-Doc#119]
**Descreva sua issue**
Ajustar CI do raw data para rodar quando um pr é fechado

**Tarefas**
- [x] Ajustar CI para PR com status de closed

**Critérios de Aceitação**
- [x] CI ajustado

**Comment by flyerjohn** [comment]
PR de ajuste ao CI aceito, ficou show!
