### ISSUE TITLE
Prototipar tela de informações

### ISSUE THREAD

**Issue by emysdias** [fga-eps-mds/2022-2-EuPescador-Doc#3]
Foi debatido de criar tela de informações no web, algo que tem no mobile mas não na aplicação web. Deve ser criado o prototipo de tela para validação. Algo parecido:

![WhatsApp_Image_2022-11-18_at_18 29 06_3](https://user-images.githubusercontent.com/52640974/204030583-59189e44-4d22-4f95-8a0f-41a88be895f3.jpeg)

**Comment by ServidioEC** [comment]
Foi feito um protótipo da tela de listagem de peixes e suas informações para validação com o Oscar.
* Acrescentou-se um botão para cadastro de uma nova espécie na listagem pelo Web que redireciona para um modal;
* Acrescentou-se um modal para cada peixe com suas informações específicas;
* Acrescentou-se um botão para editar espécie quando necessário (dentro da modal de informações do peixe).

![prototipo1](https://user-images.githubusercontent.com/52542729/204394700-5ca0dc4f-33fb-423d-9a03-4e5de0b607b9.jpg)

![prototipo2](https://user-images.githubusercontent.com/52542729/204394714-8a02cc64-48de-4b21-9451-ee4953c99b73.jpg)

![prototipo3](https://user-images.githubusercontent.com/52542729/204394727-05bb383e-4d3e-449e-b0ff-f806f68a9761.jpg)
