### ISSUE TITLE
Integrar o sistema Web com o Backend

### ISSUE THREAD

**Issue by marcelog5** [fga-eps-mds/2022-2-EuPescador-Doc#48]

**Comment by flyerjohn** [comment]
Atualizei o workflow do sonar cloud, precisamos só ficar de olho com os testes de network quebrando, por conta da nossa migração dos microsserviços ainda estar em andamento.

**Comment by marcelog5** [comment]
Subindo e executando as migrations dos micro serviços backend, foi possível executar e subir o serviço web.
